In [348]:
import numpy as np
import pandas as pd

In [349]:
df=pd.read_csv("NYC_TLC_Messy.csv")
print(df)

          TripID  VendorID    tpep_pickup_datetime   tpep_dropoff_datetime  \
0       24870114         2   03/25/2017 8:55:43 AM   03/25/2017 9:09:47 AM
1       35634249         1          04/11/17 14:53          04/11/17 15:19
2      106203690         1   12/15/2017 7:26:56 AM   12/15/2017 7:34:08 AM
3       38942136         2          05/07/17 13:17          05/07/17 13:48
4       30841670         2  04/15/2017 11:32:20 PM  04/15/2017 11:49:03 PM
...          ...       ...                     ...                     ...
22894   47368116         1   06/29/2017 7:30:30 PM   06/29/2017 7:43:29 PM
22895   84575569         2          10/08/17 02:24          10/08/17 02:59
22896   98456136         1   11/20/2017 9:59:41 AM  11/20/2017 10:07:39 AM
22897   36424085         2  04/29/2017 11:05:05 PM  04/29/2017 11:18:14 PM
22898   15752972         2   02/27/2017 8:24:37 AM   02/27/2017 8:33:42 AM

       passenger_count  trip_distance  RatecodeID store_and_fwd_flag  \
0                  6.0           3.34           1                  N
1                  1.0           1.80           1                  N
2                  1.0           1.00           1                  N
3                  1.0           3.70           1                  N
4                  NaN           4.37           1                  N
...                ...            ...         ...                ...
22894              1.0           0.00           1                  N
22895              1.0          16.40           1                  N
22896              1.0           0.70           1                  N
22897              1.0           2.66           1                  N
22898              4.0           1.48           1                  N

       PULocationID  DOLocationID  payment_type  fare_amount  extra  mta_tax  \
0               100           231             1         13.0    0.0      0.5
1               186            43             1         16.0    0.0      0.5
2               262           236             1          6.5    0.0      0.5
3               188            97             1         20.5    0.0      0.5
4                 4           112             2         16.5    0.5      0.5
...             ...           ...           ...          ...    ...      ...
22894            79           148             3          8.5    1.0      0.5
22895           151            26             2         46.0    0.5      0.5
22896           100            48             2          6.5    0.0      0.5
22897            68           114             1         11.0    0.5      0.5
22898           186           230             1          8.0    0.0      0.5

       tip_amount  tolls_amount  improvement_surcharge  total_amount
0            2.76           0.0                    0.3         16.56
1            4.00           0.0                    0.3         20.80
2            1.45           0.0                    0.3          8.75
3            6.39           0.0                    0.3         27.69
4            0.00           0.0                    0.3         17.80
...           ...           ...                    ...           ...
22894        0.00           0.0                    0.3         10.30
22895        0.00           0.0                    0.3         47.30
22896        0.00           0.0                    0.3          7.30
22897        3.08           0.0                    0.3         15.38
22898        2.20           0.0                    0.3         11.00

[22899 rows x 18 columns]

In [350]:
print(df.columns)

Index(['TripID', 'VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime',
       'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag',
       'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra',
       'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge',
       'total_amount'],
      dtype='object')

In [351]:
print(df.isnull().sum())

TripID                     0
VendorID                   0
tpep_pickup_datetime       0
tpep_dropoff_datetime      0
passenger_count          458
trip_distance              0
RatecodeID                 0
store_and_fwd_flag         0
PULocationID               0
DOLocationID               0
payment_type               0
fare_amount              688
extra                      0
mta_tax                    0
tip_amount                 0
tolls_amount               0
improvement_surcharge      0
total_amount               0
dtype: int64

In [352]:
print(df['passenger_count'].isnull().sum())
print(df['passenger_count'].head(6))

458
0    6.0
1    1.0
2    1.0
3    1.0
4    NaN
5    6.0
Name: passenger_count, dtype: float64

In [353]:
df['passenger_count']=df['passenger_count'].fillna(df['passenger_count'].median())

In [354]:
print(df['passenger_count'].isnull().sum())

0

In [355]:
print(df['passenger_count'].head(6))

0    6.0
1    1.0
2    1.0
3    1.0
4    1.0
5    6.0
Name: passenger_count, dtype: float64

In [356]:
print(df['fare_amount'].isnull().sum())

688

In [357]:
df['fare_amount']=df['fare_amount'].fillna(df['fare_amount'].median())
print(df['fare_amount'].isnull().sum())

0

In [358]:
print(df.isnull().sum())

TripID                   0
VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
dtype: int64

In [359]:
print(df['TripID'].min())
print(df['TripID'].max())
print(df['TripID'].value_counts())

12127
113486300
TripID
43550932     2
95049490     2
7175550      2
47927710     2
37705705     2
            ..
107120719    1
49074494     1
25867855     1
105261930    1
28736913     1
Name: count, Length: 22699, dtype: int64

In [360]:
print(df['VendorID'].min())
print(df['VendorID'].max())
print(df['VendorID'].value_counts())

1
2
VendorID
2    12732
1    10167
Name: count, dtype: int64

In [361]:
print("minimun no.of passengers are:",df['passenger_count'].min())
print("maximum no.of passengers are:",df['passenger_count'].max())
print(df['passenger_count'].value_counts())

minimun no.of passengers are: -2.0
maximum no.of passengers are: 6.0
passenger_count
 1.0    16359
 2.0     3281
 5.0     1121
 3.0      938
 6.0      686
 4.0      452
 0.0       32
-2.0       30
Name: count, dtype: int64

In [362]:
print(df.shape)

(22899, 18)

In [363]:
df=df[(df['passenger_count']>=1)&(df['passenger_count']<=6)]

In [364]:
print(df.shape)

(22837, 18)

In [365]:
print(df['trip_distance'].min())
print(df['trip_distance'].max())
print(df['trip_distance'].value_counts())

0.0
500.0
trip_distance
1.00     532
0.90     508
0.80     500
1.10     494
0.70     472
        ...
12.03      1
15.26      1
6.07       1
12.85      1
19.07      1
Name: count, Length: 1544, dtype: int64

In [366]:
print((df['trip_distance']==0).sum())

152

In [367]:
df=df[(df['trip_distance']>0)]
print((df['trip_distance']==0).sum())
print(df.shape)

0
(22685, 18)

In [368]:
print(df['RatecodeID'].value_counts())

RatecodeID
1    22106
2      497
3       38
5       36
4        8
Name: count, dtype: int64

In [369]:
print(df['fare_amount'].min())
print(df['fare_amount'].max())
print(df['fare_amount'].value_counts())

-120.0
9999.0
fare_amount
9.5     1517
6.0     1123
5.5     1058
6.5     1053
7.0     1036
        ...
79.5       1
90.5       1
54.5       1
73.5       1
94.2       1
Name: count, Length: 175, dtype: int64

In [370]:
df=df[(df['fare_amount']>0)]
print(df.shape)

(22668, 18)

In [371]:
print(df['total_amount'].min())
print(df['total_amount'].max())
print(df['total_amount'].value_counts())

3.3
1200.29
total_amount
7.30     545
7.80     529
6.80     524
8.30     521
8.80     497
        ...
13.44      1
36.08      1
62.16      1
35.00      1
6.55       1
Name: count, Length: 1334, dtype: int64

In [372]:
print("minimum value of extra fee:",df['extra'].min())
print("minimum value of mta_tax:",df['mta_tax'].min())
print("minimum value of tip_amount:",df['tip_amount'].min())
print("minimum value of tolls_amount:",df['tolls_amount'].min())
print("minimum value of improvemnet_surcharge:",df['improvement_surcharge'].min())

minimum value of extra fee: 0.0
minimum value of mta_tax: 0.0
minimum value of tip_amount: 0.0
minimum value of tolls_amount: 0.0
minimum value of improvemnet_surcharge: 0.3

In [373]:
print(df[['tpep_pickup_datetime','tpep_dropoff_datetime']].isna().sum())

tpep_pickup_datetime     0
tpep_dropoff_datetime    0
dtype: int64

In [374]:
df['tpep_pickup_datetime']=pd.to_datetime(df['tpep_pickup_datetime'],errors='coerce')
df['tpep_dropoff_datetime']=pd.to_datetime(df['tpep_dropoff_datetime'],errors='coerce')

In [375]:
df['trip_duration_minutes']=(df['tpep_dropoff_datetime']-df['tpep_pickup_datetime']).dt.total_seconds()/60

In [376]:
df=df.dropna(subset=['tpep_pickup_datetime','tpep_dropoff_datetime'])
print(df.shape)

(13669, 19)

In [377]:
df[['tpep_pickup_datetime','tpep_dropoff_datetime']].dtypes

tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
dtype: object

In [378]:
df['trip_duration_minutes']=(df['tpep_dropoff_datetime']-df['tpep_pickup_datetime']).dt.total_seconds()/60

In [379]:
print(df['trip_duration_minutes'])

0        14.066667
2         7.200000
4        16.716667
5         8.000000
7        21.983333
           ...
22890    21.783333
22891    10.533333
22896     7.966667
22897    13.150000
22898     9.083333
Name: trip_duration_minutes, Length: 13669, dtype: float64

In [380]:
df=df[df['trip_duration_minutes']>1]
print(df.shape)

(13618, 19)

In [381]:
df.duplicated().sum()

np.int64(123)

In [382]:
df=df.drop_duplicates()
print(df.shape)

(13495, 19)

In [383]:
zone=pd.read_csv("taxi_zone_lookup.csv")

In [384]:
df=df.merge(zone[['LocationID','Borough','Zone']],
             left_on='PULocationID',
             right_on='LocationID',
             how='left')

In [385]:
df.rename(columns={'Borough':'DO_Borough','Zone':'DO_Zone'},inplace=True)

In [386]:
df=df.merge(zone[['LocationID','Borough','Zone']],
             how='left',
             left_on='DOLocationID',
             right_on='LocationID')

In [387]:
df.rename(columns={'Borough':'PU_Borough','Zone':'PU_Zone'},inplace=True)
df.drop('LocationID_y',axis=1,inplace=True)

In [388]:
df.drop(['PULocationID','DOLocationID'],axis=1,inplace=True)

In [389]:
df

,TripID,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,...,tip_amount,tolls_amount,improvement_surcharge,total_amount,trip_duration_minutes,LocationID_x,DO_Borough,DO_Zone,PU_Borough,PU_Zone
0,24870114,2,2017-03-25 08:55:43,2017-03-25 09:09:47,6.0,3.34,1,N,1,13.0,...,2.76,0.0,0.3,16.56,14.066667,100,Manhattan,Garment District,Manhattan,TriBeCa/Civic Center
1,106203690,1,2017-12-15 07:26:56,2017-12-15 07:34:08,1.0,1.00,1,N,1,6.5,...,1.45,0.0,0.3,8.75,7.200000,262,Manhattan,Yorkville East,Manhattan,Upper East Side North
2,30841670,2,2017-04-15 23:32:20,2017-04-15 23:49:03,1.0,4.37,1,N,2,16.5,...,0.00,0.0,0.3,17.80,16.716667,4,Manhattan,Alphabet City,Brooklyn,Greenpoint
3,23345809,2,2017-03-25 20:34:11,2017-03-25 20:42:11,6.0,2.30,1,N,1,9.0,...,2.06,0.0,0.3,12.36,8.000000,161,Manhattan,Midtown Center,Manhattan,Upper East Side North
4,69059411,2,2017-08-15 17:41:06,2017-08-15 18:03:05,1.0,2.98,1,N,1,16.0,...,1.78,0.0,0.3,19.58,21.983333,237,Manhattan,Upper East Side South,Manhattan,Greenwich Village South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13490,80420727,1,2017-09-24 18:14:04,2017-09-24 18:22:36,1.0,1.30,1,N,1,7.5,...,1.65,0.0,0.3,9.95,8.533333,79,Manhattan,East Village,Manhattan,Midtown South
13491,44531431,2,2017-05-24 10:13:43,2017-05-24 10:31:34,1.0,2.79,1,n,2,13.5,...,0.00,0.0,0.3,14.30,17.850000,226,Queens,Sunnyside,Queens,Steinway
13492,69393675,2,2017-08-16 20:17:35,2017-08-16 20:25:48,3.0,1.15,1,N,1,7.0,...,1.66,0.0,0.3,9.96,8.216667,161,Manhattan,Midtown Center,Manhattan,Penn Station/Madison Sq West
13493,81511935,2,2017-09-28 11:36:30,2017-09-28 11:49:58,5.0,1.93,1,N,1,10.5,...,2.82,0.0,0.3,14.12,13.466667,142,Manhattan,Lincoln Square East,Manhattan,Upper West Side North
13494,63965316,2,2017-07-28 07:12:44,2017-07-28 07:31:39,2.0,2.01,1,N,1,13.5,...,2.14,0.0,0.3,21.39,18.916667,229,Manhattan,Sutton Place/Turtle Bay North,Manhattan,Lincoln Square East

In [390]:
df.isnull().sum()

TripID                     0
VendorID                   0
tpep_pickup_datetime       0
tpep_dropoff_datetime      0
passenger_count            0
trip_distance              0
RatecodeID                 0
store_and_fwd_flag         0
payment_type               0
fare_amount                0
extra                      0
mta_tax                    0
tip_amount                 0
tolls_amount               0
improvement_surcharge      0
total_amount               0
trip_duration_minutes      0
LocationID_x               0
DO_Borough                 3
DO_Zone                  183
PU_Borough                36
PU_Zone                  156
dtype: int64

In [391]:
df['DO_Borough'].fillna('unknown',inplace=True)
df['DO_Zone'].fillna('unknown',inplace=True)
df['PU_Borough'].fillna('unknown',inplace=True)
df['PU_Zone'].fillna('unknown',inplace=True)

/tmp/ipykernel_4469/286710025.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DO_Borough'].fillna('unknown',inplace=True)
/tmp/ipykernel_4469/286710025.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DO_Zone'].fillna('unknown',inplace=True)
/tmp/ipykernel_4469/286710025.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['PU_Borough'].fillna('unknown',inplace=True)
/tmp/ipykernel_4469/286710025.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['PU_Zone'].fillna('unknown',inplace=True)

In [392]:
df.isnull().sum()

TripID                   0
VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
trip_duration_minutes    0
LocationID_x             0
DO_Borough               0
DO_Zone                  0
PU_Borough               0
PU_Zone                  0
dtype: int64

In [393]:
print("do_borough:",df['DO_Borough'].unique())
print("do_zone:",df['DO_Zone'].unique())
print("pu_borough:",df['PU_Borough'].unique())
print("pu_zone:",df['PU_Zone'].unique())

do_borough: ['Manhattan' 'Queens' 'Brooklyn' 'Unknown' 'unknown' 'Bronx'
 'Staten Island']
do_zone: ['Garment District' 'Yorkville East' 'Alphabet City' 'Midtown Center'
 'Upper East Side South' 'Upper West Side North' 'Midtown North'
 'Morningside Heights' 'Midtown East' 'Central Park' 'JFK Airport'
 'Times Sq/Theatre District' 'Lincoln Square East' 'Lenox Hill East'
 'Flatiron' 'Murray Hill' 'Union Sq' 'West Village'
 'Upper West Side South' 'West Chelsea/Hudson Yards' 'Yorkville West'
 'Manhattan Valley' 'LaGuardia Airport' 'Upper East Side North'
 'East Chelsea' 'Gramercy' 'Clinton East' 'East Village'
 'Greenwich Village South' 'Financial District North' 'Hudson Sq'
 'Penn Station/Madison Sq West' 'Greenwich Village North'
 'Williamsburg (South Side)' 'TriBeCa/Civic Center' 'UN/Turtle Bay South'
 'East Harlem South' 'East Harlem North' 'Meatpacking/West Village West'
 'Sutton Place/Turtle Bay North' 'Lower East Side' 'Clinton West'
 'Little Italy/NoLiTa' 'Midtown South' 'unknown' 'Briarwood/Jamaica Hills'
 'Bloomingdale' 'Battery Park City' 'Park Slope' 'Lenox Hill West'
 'Kips Bay' 'Lincoln Square West' 'Bedford' 'Williamsburg (North Side)'
 'Central Harlem North' 'Sunnyside' 'Central Harlem' 'World Trade Center'
 'SoHo' 'Clinton Hill' 'Hamilton Heights' 'Prospect Park'
 'Financial District South' 'Stuy Town/Peter Cooper Village' 'Rego Park'
 'Outside of NYC' 'Fort Greene' 'Washington Heights South' 'Chinatown'
 'Brooklyn Heights' 'Downtown Brooklyn/MetroTech' 'Carroll Gardens'
 'East Williamsburg' 'Two Bridges/Seward Park' 'Bushwick South' 'Astoria'
 'Boerum Hill' 'Elmhurst/Maspeth' 'Prospect-Lefferts Gardens'
 'Crown Heights North' 'Jamaica' 'Jackson Heights' 'Woodside'
 'Long Island City/Queens Plaza' 'Steinway' 'Corona'
 'Long Island City/Hunters Point' 'Flushing Meadows-Corona Park'
 'Manhattanville' 'Queensbridge/Ravenswood' 'Inwood' 'Gowanus'
 'Cobble Hill' 'Fordham South' 'Seaport' 'Flushing' 'Old Astoria'
 'Inwood Hill Park' 'East Elmhurst' 'Sunset Park West' 'Brownsville'
 'DUMBO/Vinegar Hill' 'Cypress Hills' 'Bushwick North' 'City Island'
 'Flatlands' 'Heartland Village/Todt Hill' 'Erasmus' 'Crown Heights South'
 'Greenpoint' 'East Tremont' 'Elmhurst' 'Prospect Heights'
 'Washington Heights North' 'South Ozone Park' 'Forest Hills'
 'North Corona' 'West Concourse' 'Stuyvesant Heights' 'Columbia Street'
 'University Heights/Morris Heights' 'Homecrest' 'Battery Park'
 'Soundview/Castle Hill' 'Woodhaven' 'Brighton Beach' 'South Jamaica'
 'Pelham Parkway' 'Springfield Gardens North' 'Kew Gardens Hills'
 'Marble Hill']
pu_borough: ['Manhattan' 'Brooklyn' 'Queens' 'Bronx' 'unknown' 'EWR' 'Unknown'
 'Staten Island']
pu_zone: ['TriBeCa/Civic Center' 'Upper East Side North' 'Greenpoint'
 'Greenwich Village South' 'Midtown Center' 'Central Harlem'
 'Upper West Side North' 'Yorkville West' 'Upper East Side South'
 'Lenox Hill West' 'Greenwich Village North' 'Madison'
 'Lincoln Square East' 'East Village' 'SoHo' 'Times Sq/Theatre District'
 'Gramercy' 'Financial District South' 'Upper West Side South'
 'Fort Greene' 'Clinton West' 'Garment District'
 'Sutton Place/Turtle Bay North' 'West Chelsea/Hudson Yards'
 'Bloomingdale' 'Williamsburg (North Side)' 'Ozone Park'
 'East Harlem North' 'Union Sq' 'Midtown South'
 'Penn Station/Madison Sq West' 'Midtown East' 'Windsor Terrace'
 'Murray Hill' 'Financial District North' 'Co-Op City'
 'UN/Turtle Bay South' 'LaGuardia Airport' 'East Chelsea'
 'Two Bridges/Seward Park' 'Park Slope' 'Hudson Sq'
 'Meatpacking/West Village West' 'Midtown North' 'Steinway' 'Central Park'
 'Outside of NYC' 'Lenox Hill East' 'Bedford' 'West Village' 'Kips Bay'
 'Flatiron' 'Springfield Gardens South' 'Newark Airport'
 'Hamilton Heights' 'unknown' 'Forest Hills' 'Lower East Side'
 'Morningside Heights' 'Battery Park City' 'East Harlem South'
 'Hillcrest/Pomonok' 'Stuyvesant Heights' 'Mott Haven/Port Morris'
 'Clinton East' 'Little Italy/NoLiTa' 'Bushwick South' 'Parkchester'
 'Crown Heights North' 'Yorkville East' 'Long Island City/Hunters Point'
 'Roosevelt Island' 'Manhattan Valley' 'Gowanus' 'Central Harlem North'
 'JFK Airport' 'Kensington' 'Astoria' 'Flatbush/Ditmas Park'
 'Coney Island' 'Washington Heights South' 'Lincoln Square West'
 'World Trade Center' 'Sunnyside' 'Red Hook' 'Alphabet City'
 'Stuy Town/Peter Cooper Village' 'Elmhurst/Maspeth'
 'Washington Heights North' 'Boerum Hill' 'Jackson Heights' 'Chinatown'
 'Canarsie' 'Seaport' 'Kew Gardens' 'Williamsburg (South Side)'
 'Brooklyn Heights' 'Highbridge' 'East Flatbush/Remsen Village'
 'Melrose South' 'DUMBO/Vinegar Hill' 'Battery Park' 'Brownsville'
 'Bushwick North' 'East Williamsburg' 'Manhattanville' 'Cobble Hill'
 'Oakland Gardens' 'Glendale' 'Ridgewood' 'Spuyten Duyvil/Kingsbridge'
 'Clinton Hill' 'Downtown Brooklyn/MetroTech' 'College Point' 'Elmhurst'
 'Prospect Heights' 'Saint Michaels Cemetery/Woodside' 'Erasmus'
 'Longwood' 'Bay Ridge' 'Bronx Park' 'Cypress Hills' 'Crown Heights South'
 'Briarwood/Jamaica Hills' 'Bedford Park' 'Queensbridge/Ravenswood'
 'Old Astoria' 'Inwood' 'Woodside' 'Jamaica'
 'East Concourse/Concourse Village' 'Soundview/Bruckner'
 'Kingsbridge Heights' 'Bensonhurst East' 'West Concourse'
 'West Farms/Bronx River' 'Carroll Gardens' 'Manhattan Beach'
 'Van Cortlandt Village' 'Rego Park' 'Flushing' 'East Elmhurst'
 'Ocean Hill' 'Maspeth' 'Woodlawn/Wakefield' 'Soundview/Castle Hill'
 'Prospect-Lefferts Gardens' 'University Heights/Morris Heights'
 'Long Island City/Queens Plaza' 'East New York/Pennsylvania Avenue'
 'Randalls Island' 'Sunset Park West' 'Hammels/Arverne' 'Columbia Street'
 'Richmond Hill' 'Riverdale/North Riverdale/Fieldston' 'Douglaston'
 'Jamaica Estates' 'Sunset Park East' 'Sheepshead Bay' 'Far Rockaway'
 'Crotona Park East' 'Borough Park' 'Fresh Meadows' 'Woodhaven'
 'Hunts Point' 'Ocean Parkway South' 'Whitestone' 'Norwood' 'Homecrest'
 'Middle Village' 'Flushing Meadows-Corona Park'
 'Heartland Village/Todt Hill' 'South Ozone Park' 'Pelham Bay Park'
 'Saint Albans' 'Murray Hill-Queens' 'East Tremont' 'Kew Gardens Hills'
 'South Williamsburg' 'South Jamaica' 'Marble Hill' 'East New York'
 'Bronxdale' 'Mount Hope' 'Bath Beach' 'Van Cortlandt Park'
 'Claremont/Bathgate' 'Springfield Gardens North' 'North Corona'
 'Cambria Heights' 'Flatlands' 'Pelham Bay' 'Bay Terrace/Fort Totten'
 'Bayside' 'Bensonhurst West' 'Dyker Heights' 'Bloomfield/Emerson Hill'
 'Howard Beach' 'Baisley Park' 'Fordham South'
 'Schuylerville/Edgewater Park' 'Prospect Park']

In [394]:
df['VendorID']=df['VendorID'].astype('category')
df['RatecodeID']=df['RatecodeID'].astype('category')
df['payment_type']=df['payment_type'].astype('category')
df['VendorID']=df['VendorID'].astype('category')

In [395]:
df.dtypes

TripID                            int64
VendorID                       category
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                 float64
trip_distance                   float64
RatecodeID                     category
store_and_fwd_flag               object
payment_type                   category
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
trip_duration_minutes           float64
LocationID_x                      int64
DO_Borough                       object
DO_Zone                          object
PU_Borough                       object
PU_Zone                          object
dtype: object

In [396]:
df['store_and_fwd_flag']=df['store_and_fwd_flag'].astype(str)
df['passenger_count']=df['passenger_count'].astype(int)

In [397]:
df.dtypes

TripID                            int64
VendorID                       category
tpep_pickup_datetime     datetime64[ns]
tpep_dropoff_datetime    datetime64[ns]
passenger_count                   int64
trip_distance                   float64
RatecodeID                     category
store_and_fwd_flag               object
payment_type                   category
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
trip_duration_minutes           float64
LocationID_x                      int64
DO_Borough                       object
DO_Zone                          object
PU_Borough                       object
PU_Zone                          object
dtype: object

In [398]:
df['store_and_fwd_flag']=df['store_and_fwd_flag'].map({'N':0,'Y':1})

In [399]:
print(df)

          TripID VendorID tpep_pickup_datetime tpep_dropoff_datetime  \
0       24870114        2  2017-03-25 08:55:43   2017-03-25 09:09:47
1      106203690        1  2017-12-15 07:26:56   2017-12-15 07:34:08
2       30841670        2  2017-04-15 23:32:20   2017-04-15 23:49:03
3       23345809        2  2017-03-25 20:34:11   2017-03-25 20:42:11
4       69059411        2  2017-08-15 17:41:06   2017-08-15 18:03:05
...          ...      ...                  ...                   ...
13490   80420727        1  2017-09-24 18:14:04   2017-09-24 18:22:36
13491   44531431        2  2017-05-24 10:13:43   2017-05-24 10:31:34
13492   69393675        2  2017-08-16 20:17:35   2017-08-16 20:25:48
13493   81511935        2  2017-09-28 11:36:30   2017-09-28 11:49:58
13494   63965316        2  2017-07-28 07:12:44   2017-07-28 07:31:39

       passenger_count  trip_distance RatecodeID  store_and_fwd_flag  \
0                    6           3.34          1                 0.0
1                    1           1.00          1                 0.0
2                    1           4.37          1                 0.0
3                    6           2.30          1                 0.0
4                    1           2.98          1                 0.0
...                ...            ...        ...                 ...
13490                1           1.30          1                 0.0
13491                1           2.79          1                 NaN
13492                3           1.15          1                 0.0
13493                5           1.93          1                 0.0
13494                2           2.01          1                 0.0

      payment_type  fare_amount  ...  tip_amount  tolls_amount  \
0                1         13.0  ...        2.76           0.0
1                1          6.5  ...        1.45           0.0
2                2         16.5  ...        0.00           0.0
3                1          9.0  ...        2.06           0.0
4                1         16.0  ...        1.78           0.0
...            ...          ...  ...         ...           ...
13490            1          7.5  ...        1.65           0.0
13491            2         13.5  ...        0.00           0.0
13492            1          7.0  ...        1.66           0.0
13493            1         10.5  ...        2.82           0.0
13494            1         13.5  ...        2.14           0.0

       improvement_surcharge  total_amount  trip_duration_minutes  \
0                        0.3         16.56              14.066667
1                        0.3          8.75               7.200000
2                        0.3         17.80              16.716667
3                        0.3         12.36               8.000000
4                        0.3         19.58              21.983333
...                      ...           ...                    ...
13490                    0.3          9.95               8.533333
13491                    0.3         14.30              17.850000
13492                    0.3          9.96               8.216667
13493                    0.3         14.12              13.466667
13494                    0.3         21.39              18.916667

       LocationID_x  DO_Borough                        DO_Zone PU_Borough  \
0               100   Manhattan               Garment District  Manhattan
1               262   Manhattan                 Yorkville East  Manhattan
2                 4   Manhattan                  Alphabet City   Brooklyn
3               161   Manhattan                 Midtown Center  Manhattan
4               237   Manhattan          Upper East Side South  Manhattan
...             ...         ...                            ...        ...
13490            79   Manhattan                   East Village  Manhattan
13491           226      Queens                      Sunnyside     Queens
13492           161   Manhattan                 Midtown Center  Manhattan
13493           142   Manhattan            Lincoln Square East  Manhattan
13494           229   Manhattan  Sutton Place/Turtle Bay North  Manhattan

                            PU_Zone
0              TriBeCa/Civic Center
1             Upper East Side North
2                        Greenpoint
3             Upper East Side North
4           Greenwich Village South
...                             ...
13490                 Midtown South
13491                      Steinway
13492  Penn Station/Madison Sq West
13493         Upper West Side North
13494           Lincoln Square East

[13495 rows x 22 columns]

In [400]:
df['PU_Zone_freq']=df['PU_Zone'].map(df['PU_Zone'].value_counts())
df['DO_Zone_freq']=df['DO_Zone'].map(df['DO_Zone'].value_counts())

In [401]:
df

,TripID,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,...,improvement_surcharge,total_amount,trip_duration_minutes,LocationID_x,DO_Borough,DO_Zone,PU_Borough,PU_Zone,PU_Zone_freq,DO_Zone_freq
0,24870114,2,2017-03-25 08:55:43,2017-03-25 09:09:47,6,3.34,1,0.0,1,13.0,...,0.3,16.56,14.066667,100,Manhattan,Garment District,Manhattan,TriBeCa/Civic Center,255,279
1,106203690,1,2017-12-15 07:26:56,2017-12-15 07:34:08,1,1.00,1,0.0,1,6.5,...,0.3,8.75,7.200000,262,Manhattan,Yorkville East,Manhattan,Upper East Side North,481,153
2,30841670,2,2017-04-15 23:32:20,2017-04-15 23:49:03,1,4.37,1,0.0,2,16.5,...,0.3,17.80,16.716667,4,Manhattan,Alphabet City,Brooklyn,Greenpoint,31,34
3,23345809,2,2017-03-25 20:34:11,2017-03-25 20:42:11,6,2.30,1,0.0,1,9.0,...,0.3,12.36,8.000000,161,Manhattan,Midtown Center,Manhattan,Upper East Side North,481,519
4,69059411,2,2017-08-15 17:41:06,2017-08-15 18:03:05,1,2.98,1,0.0,1,16.0,...,0.3,19.58,21.983333,237,Manhattan,Upper East Side South,Manhattan,Greenwich Village South,159,534
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13490,80420727,1,2017-09-24 18:14:04,2017-09-24 18:22:36,1,1.30,1,0.0,1,7.5,...,0.3,9.95,8.533333,79,Manhattan,East Village,Manhattan,Midtown South,290,382
13491,44531431,2,2017-05-24 10:13:43,2017-05-24 10:31:34,1,2.79,1,NaN,2,13.5,...,0.3,14.30,17.850000,226,Queens,Sunnyside,Queens,Steinway,26,25
13492,69393675,2,2017-08-16 20:17:35,2017-08-16 20:25:48,3,1.15,1,0.0,1,7.0,...,0.3,9.96,8.216667,161,Manhattan,Midtown Center,Manhattan,Penn Station/Madison Sq West,398,519
13493,81511935,2,2017-09-28 11:36:30,2017-09-28 11:49:58,5,1.93,1,0.0,1,10.5,...,0.3,14.12,13.466667,142,Manhattan,Lincoln Square East,Manhattan,Upper West Side North,261,377
13494,63965316,2,2017-07-28 07:12:44,2017-07-28 07:31:39,2,2.01,1,0.0,1,13.5,...,0.3,21.39,18.916667,229,Manhattan,Sutton Place/Turtle Bay North,Manhattan,Lincoln Square East,370,270

In [402]:
df=pd.get_dummies(df,columns=['PU_Borough','DO_Borough'],drop_first=True)

In [403]:
df

,TripID,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,...,PU_Borough_Queens,PU_Borough_Staten Island,PU_Borough_Unknown,PU_Borough_unknown,DO_Borough_Brooklyn,DO_Borough_Manhattan,DO_Borough_Queens,DO_Borough_Staten Island,DO_Borough_Unknown,DO_Borough_unknown
0,24870114,2,2017-03-25 08:55:43,2017-03-25 09:09:47,6,3.34,1,0.0,1,13.0,...,False,False,False,False,False,True,False,False,False,False
1,106203690,1,2017-12-15 07:26:56,2017-12-15 07:34:08,1,1.00,1,0.0,1,6.5,...,False,False,False,False,False,True,False,False,False,False
2,30841670,2,2017-04-15 23:32:20,2017-04-15 23:49:03,1,4.37,1,0.0,2,16.5,...,False,False,False,False,False,True,False,False,False,False
3,23345809,2,2017-03-25 20:34:11,2017-03-25 20:42:11,6,2.30,1,0.0,1,9.0,...,False,False,False,False,False,True,False,False,False,False
4,69059411,2,2017-08-15 17:41:06,2017-08-15 18:03:05,1,2.98,1,0.0,1,16.0,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13490,80420727,1,2017-09-24 18:14:04,2017-09-24 18:22:36,1,1.30,1,0.0,1,7.5,...,False,False,False,False,False,True,False,False,False,False
13491,44531431,2,2017-05-24 10:13:43,2017-05-24 10:31:34,1,2.79,1,NaN,2,13.5,...,True,False,False,False,False,False,True,False,False,False
13492,69393675,2,2017-08-16 20:17:35,2017-08-16 20:25:48,3,1.15,1,0.0,1,7.0,...,False,False,False,False,False,True,False,False,False,False
13493,81511935,2,2017-09-28 11:36:30,2017-09-28 11:49:58,5,1.93,1,0.0,1,10.5,...,False,False,False,False,False,True,False,False,False,False
13494,63965316,2,2017-07-28 07:12:44,2017-07-28 07:31:39,2,2.01,1,0.0,1,13.5,...,False,False,False,False,False,True,False,False,False,False

In [404]:
bool_cols=df.select_dtypes(include='bool').columns
for col in bool_cols:
    df[col]=df[col].map({True:1,False:0})

In [405]:
df

,TripID,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,fare_amount,...,PU_Borough_Queens,PU_Borough_Staten Island,PU_Borough_Unknown,PU_Borough_unknown,DO_Borough_Brooklyn,DO_Borough_Manhattan,DO_Borough_Queens,DO_Borough_Staten Island,DO_Borough_Unknown,DO_Borough_unknown
0,24870114,2,2017-03-25 08:55:43,2017-03-25 09:09:47,6,3.34,1,0.0,1,13.0,...,0,0,0,0,0,1,0,0,0,0
1,106203690,1,2017-12-15 07:26:56,2017-12-15 07:34:08,1,1.00,1,0.0,1,6.5,...,0,0,0,0,0,1,0,0,0,0
2,30841670,2,2017-04-15 23:32:20,2017-04-15 23:49:03,1,4.37,1,0.0,2,16.5,...,0,0,0,0,0,1,0,0,0,0
3,23345809,2,2017-03-25 20:34:11,2017-03-25 20:42:11,6,2.30,1,0.0,1,9.0,...,0,0,0,0,0,1,0,0,0,0
4,69059411,2,2017-08-15 17:41:06,2017-08-15 18:03:05,1,2.98,1,0.0,1,16.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13490,80420727,1,2017-09-24 18:14:04,2017-09-24 18:22:36,1,1.30,1,0.0,1,7.5,...,0,0,0,0,0,1,0,0,0,0
13491,44531431,2,2017-05-24 10:13:43,2017-05-24 10:31:34,1,2.79,1,NaN,2,13.5,...,1,0,0,0,0,0,1,0,0,0
13492,69393675,2,2017-08-16 20:17:35,2017-08-16 20:25:48,3,1.15,1,0.0,1,7.0,...,0,0,0,0,0,1,0,0,0,0
13493,81511935,2,2017-09-28 11:36:30,2017-09-28 11:49:58,5,1.93,1,0.0,1,10.5,...,0,0,0,0,0,1,0,0,0,0
13494,63965316,2,2017-07-28 07:12:44,2017-07-28 07:31:39,2,2.01,1,0.0,1,13.5,...,0,0,0,0,0,1,0,0,0,0

In [406]:
df.to_csv('taxi10.csv',index=False)